# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calculateScoresDense <- function(orig_mat, gene_indices) {
    .Call(`_genefunnel_calculateScoresDense`, orig_mat, gene_indices)
}

calculateScoresSparse <- function(orig_mat, gene_indices) {
    .Call(`_genefunnel_calculateScoresSparse`, orig_mat, gene_indices)
}

calculateComponentsDense <- function(orig_mat, gene_indices) {
    .Call(`_genefunnel_calculateComponentsDense`, orig_mat, gene_indices)
}

calculateComponentsSparse <- function(orig_mat, gene_indices) {
    .Call(`_genefunnel_calculateComponentsSparse`, orig_mat, gene_indices)
}

