# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calculateScores <- function(orig_mat, row_names, gene_ids) {
    .Call(`_genefunnel_calculateScores`, orig_mat, row_names, gene_ids)
}

